# Site
title: Alex Jover
subtitle: Software & javascript tips and tricks!
description: Articles about modern javascript tips, tools, and tricks!
author: Alex Jover Morales
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://alexjoverm.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'okaidia'
  line_number: false
highlight:
  enable: false

# Category & Tag
default_category: uncategorized
tag_generator:
  per_page: 10
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 15
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: beautiful-hexo

archive_generator:
    per_page: 0
    yearly: false
    monthly: false
    daily: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/alexjoverm/alexjoverm.github.io
  branch: master

algolia:
  applicationID: 6252178E0A
  apiKey: ead5c5a5a82108a54f04c9f610a54ee2
  indexName: blog

series:
  enabled: true
  folder: series

# Redirects
alias:
  index.html: https://alexjover.com/
  about/index.html: https://alexjover.com/about/
  2017/09/11/Test-Properties-and-Custom-Events-in-Vue-js-Components-with-Jest/index.html: https://alexjover.com/blog/2017/09/11/Test-Properties-and-Custom-Events-in-Vue-js-Components-with-Jest/
  2017/08/21/Write-the-first-Vue-js-Component-Unit-Test-in-Jest/index.html: https://alexjover.com/blog/2017/08/21/Write-the-first-Vue-js-Component-Unit-Test-in-Jest/
  2017/11/21/1-year-organising-Alicante-Frontend/index.html: https://alexjover.com/blog/2017/11/21/1-year-organising-Alicante-Frontend/
  2017/11/13/My-tips-to-be-a-happier-developer/index.html: https://alexjover.com/blog/2017/11/13/My-tips-to-be-a-happier-developer/
  2017/10/07/Enhance-Jest-configuration-with-Module-Aliases/index.html: https://alexjover.com/blog/2017/10/07/Enhance-Jest-configuration-with-Module-Aliases/
  2017/10/02/Test-Vue-js-Slots-in-Jest/index.html: https://alexjover.com/blog/2017/10/02/Test-Vue-js-Slots-in-Jest/
  2017/09/25/Test-Methods-and-Mock-Dependencies-in-Vue-js-with-Jest/index.html: https://alexjover.com/blog/2017/09/25/Test-Methods-and-Mock-Dependencies-in-Vue-js-with-Jest/
  2017/08/28/Test-Deeply-Rendered-Vue-js-Components-in-Jest/index.html: https://alexjover.com/blog/2017/08/28/Test-Deeply-Rendered-Vue-js-Components-in-Jest/
  2017/09/18/Test-Computed-Properties-and-Watchers-in-Vue-js-Components-with-Jest/index.html: https://alexjover.com/blog/2017/09/18/Test-Computed-Properties-and-Watchers-in-Vue-js-Components-with-Jest/
  2017/09/04/Test-Styles-and-Structure-of-Vue-js-Components-in-Jest/index.html: https://alexjover.com/blog/2017/09/04/Test-Styles-and-Structure-of-Vue-js-Components-in-Jest/
  2017/08/14/Apply-infinite-operations-to-an-RxJS-Observable/index.html: https://alexjover.com/blog/2017/08/14/Apply-infinite-operations-to-an-RxJS-Observable/
  2017/03/23/Apollo-GraphQL-and-Nuxt-shenanigans/index.html: https://alexjover.com/blog/2017/03/23/Apollo-GraphQL-and-Nuxt-shenanigans/
  2017/08/07/How-I-made-a-Progressive-Web-App-out-of-my-Blog/index.html: https://alexjover.com/blog/2017/08/07/How-I-made-a-Progressive-Web-App-out-of-my-Blog/
  2017/07/16/Lazy-load-in-Vue-using-Webpack-s-code-splitting/index.html: https://alexjover.com/blog/2017/07/16/Lazy-load-in-Vue-using-Webpack-s-code-splitting/
  2017/06/28/Integrate-TypeScript-in-your-Vue-project/index.html: https://alexjover.com/blog/2017/06/28/Integrate-TypeScript-in-your-Vue-project/
  2017/06/12/Use-Prettier-with-TSLint-and-be-happy/index.html: https://alexjover.com/blog/2017/06/12/Use-Prettier-with-TSLint-and-be-happy/
  2017/04/11/Typescript-Lookup-Types-type-safe-properties/index.html: https://alexjover.com/blog/2017/04/11/Typescript-Lookup-Types-type-safe-properties/
  2017/03/06/Tree-shaking-with-Webpack-2-TypeScript-and-Babel/index.html: https://alexjover.com/blog/2017/03/06/Tree-shaking-with-Webpack-2-TypeScript-and-Babel/
  tags/index.html: https://alexjover.com/blog/tags/
  archives/index.html: https://alexjover.com/blog/archives/
  series/index.html: https://alexjover.com/blog/series/
  series/Unit-Testing-Vue-js-Components-with-the-Official-Vue-Testing-Tools-and-Jest/index.html: https://alexjover.com/blog/series/Unit-Testing-Vue-js-Components-with-the-Official-Vue-Testing-Tools-and-Jest/
