navbar-links:
    Videos:
      link: https://egghead.io/instructors/alex-jover-morales
    Series: /series
    # Tags: /tags
    Archive: /archives
    About: /about

avatar: /alex.jpg
favicon: /alex.jpg

header:
    title: "Alex Jover"
    motto: Software & javascript tips and tricks!
    bigimgs:
        - src: /bigimgs/meetup1.jpg
          desc:

rss: /atom.xml
googlefonts:
  - "Open+Sans:400italic,600italic,700italic,400,600,700"

links:
  rss:
    link: '/atom.xml'
    title: RSS
    icon: fa-rss
    enable: true
  twitter:
    link: 'https://twitter.com/alexjoverm'
    title: Twitter
    icon: fa-twitter
    enable: true
  github:
    link: 'https://github.com/alexjoverm'
    title: GitHub
    icon: fa-github
    enable: true
  linkin:
    link: https://www.linkedin.com/in/alex-jover-morales-994752102/
    title: LinkedIn
    icon: fa-linkedin
    enable: true
  stackoverflow:
    link: http://stackoverflow.com/users/4191146/alex-jm
    title: StackOverflow
    icon: fa-stack-overflow
    enable: true

google_analytics: UA-93226517-1

comment:
  enable: true
  disqus: alexjm-blog

